import type { Metadata } from 'next';
import { Jua, Nanum_Gothic_Coding, Poetsen_One } from 'next/font/google';
import '../styles/globals.scss';
import '../styles/Home.scss';
import Header from '@/components/Header';

const jua = Jua({
  variable: '--font-jua',
  subsets: ['latin'],
  weight: '400',
});

const nanumGothicCoding = Nanum_Gothic_Coding({
  variable: '--font-nanum-gothic-coding',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const poesenOne = Poetsen_One({
  variable: '--font-poesen-one',
  weight: '400',
});

export const metadata: Metadata = {
  title: `프론트엔드 개발자 김지민 포트폴리오 :: Bluemin's portfolio`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${jua.variable} ${nanumGothicCoding.variable} ${poesenOne.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
