import type { Metadata } from 'next';
import { Jua } from 'next/font/google';
import '../styles/globals.scss';
import '../styles/LandingPage.scss';

const jua = Jua({
  variable: '--font-jua',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: `프론트엔드 개발자 김지민 포트폴리오 :: Bluemin's portfolio`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jua.variable}`}>{children}</body>
    </html>
  );
}
